### ISSUE TITLE
"Crouching" when someone teleports

### ISSUE THREAD

**Issue by Scooke96** [NillerMedDild/Enigmatica6#1527]
I have no idea how to replicate this but we are one 0.4.2 has been an issue since 0.3.10 someone will TPA or /home and anyone in that area will "crouch". I put speech marks because the player model doesnt crouch but the players name will go lower as if crouching and the player view will be like crouching too

**Comment by NillerMedDild** [comment]
What the actual :P Thanks for the report, will investigate. That being said I have base with my wife on the official server and we've never seen this issue, so I doubt I'll be able to reproduce it.

**Comment by Scooke96** [comment]
If you wanted to pop into my server to experience it lemme know

**Comment by NillerMedDild** [comment]
Have you added any mods?

**Comment by Scooke96** [comment]
Nope, no extra mods

**Comment by theboo** [comment]
I've seen similar complaints from the Shrink! Mod but I could never repro it myself

**Comment by shibeobi12** [comment]
Wanted to chime in; I've seen this and experienced it myself on 0.4.2, but my attempts to pin down what causes it has failed so far.

**Comment by AlienXAXS** [comment]
Just my two cents here and I have a way of replicating it:

- Have a friend be just outside of render distance
- Have that friend walk towards you, as soon as you render that player, your camera will crouch.

**Comment by ochotonida** [comment]
If I'm not mistaken, I believe issue only occurs if you've used the shrinking device from the Shrink mod before on your world. Might need some testing though.

**Comment by AlienXAXS** [comment]
> If I'm not mistaken, I believe issue only occurs if you've used the shrinking device from the Shrink mod before on your world. Might need some testing though.

Perfect mate, just did some more testing - if the player has shrunk themselves in the past, their camera will become modified when another player is rendered into view.

I tested this as:

1. /execute in compactmachines:compact_world run tp AlienXAXS ~ ~ ~ (teleporting myself into a void world, to ensure no other blocks were being funky)
2. /setblock ~ ~ ~ stone
3. Teleported my friend in, whom had never used the shrinking device before.
4. Tested them by moving in and out of their render range with fly mode
5. Gave them the shrink device, they shrunk themselves and unshrunk themselves
6. Bug now appears whenever i fly into view.

@NillerMedDild - just highlighting you to ensure you see this.

**Comment by theboo** [comment]
https://github.com/gigabit101/Shrink/issues/18

**Comment by Scooke96** [comment]
Just wanted to update just in case this has been fixed in version 1.1.0 of Shrink

**Comment by xATL4S** [comment]
I don't know if this is marked fixed for a future release 0.4.11 etc 
But I am definitely still getting this issue on 0.4.10 - typically after a teleport, or switching from spectator to survival. One note is this is affecting my view height rather than a visual bug showing me crouched when not. (View height as in it looks like I am about 1.25 / 1.5 blocks in height)

**Comment by Darkere** [comment]
Fix was made just never released it looks like.

**Comment by 486dx33mhz** [comment]
This bug is still happening for a friend of mine on my server(0.5.0). we have tried a lot of different things to fix the issue, including: Relogs, dying, changing dimension, sitting on a mount then dismounting and restarting the server.

**Comment by endorphinrush** [comment]
@NillerMedDild I saw you posted on the mod owners site but wanted to confirm that I was previously seeing this in 0.4.1 and am now seeing it in 0.5.4.

0.4.1 was running Shrink 1.0.7 - View height was affected but could be returned to normal by crouching and sometimes relogging.

0.5.4 is running Shrink 1.1.0 - After updating from 0.4.1 I was permanently stuck in "crouch view". Player model in third person view showed the player standing and crouching normally. In first person mode the player was stuck in crouch view no matter how many times you pressed the crouch key.

If it matters I'm hosting Enigmatica on a dedicated local Windows 7 box. Two players joining. Only the player that used the Shrinking device is affected.

It seems I've been able to mitigate this by rolling back to Shrink 1.0.5
