### ISSUE TITLE
[Mod Suggestion] FramedBlocks

### ISSUE THREAD

**Issue by MrBazlow** [NillerMedDild/Enigmatica6#2171]
**CurseForge Link**
https://www.curseforge.com/minecraft/mc-mods/framedblocks

**Mod description**
Adds various shaped blocks for architecture

**Why would you like the mod added?**
Unlike BlockCarpentry, the sloped blocks can be placed horizontally or vertically, the framed ladder works as an actual ladder you can climb and the textures on sloped blocks display better than BlockCarpentry blocks.

**Screenshots if applicable.**
![2021-05-14_23 00 37](https://user-images.githubusercontent.com/67396813/118335807-57a92200-b508-11eb-8ca4-0a1f6afa2629.png)

![2021-05-14_23 00 51](https://user-images.githubusercontent.com/67396813/118335828-6263b700-b508-11eb-9e2d-18d6b8bb5642.png)

**Comment by NillerMedDild** [comment]
I'll be swapping BlockCarpentry with this in 0.5.0 :) thanks for the suggestion.

**Comment by Erysch** [comment]
Well, I swapped out the mods already and noticed that the pressure plates do not work properly . The door didn't really move or only one half of it (i used the industrial iron door from 'Dustrial Decor) . I didn't do further testing. Also the slope block placement for roofs is annoying since it it's based on the block side you click on. So building mid-air is annoying. Block carpentry slopes connect automatically where FramedBlock's do not. At the end it's a matter of taste-

**Comment by MrBazlow** [comment]
> Well, I swapped out the mods already and noticed that the pressure plates do not work properly . The door didn't really move or only one half of it (i used the industrial iron door from 'Dustrial Decor) . 

This sounds like it is working properly, to open a double door you need two pressure plates for each door unless you want to have some redstone below passing the signal along. I just tested it with 'Dustrial Decor iron doors, wooden doors, iron doors, stone pressure plates, framed blocks pressure plates and blockcarpentry pressure plates. They all work the same

> Also the slope block placement for roofs is annoying since it it's based on the block side you click on. So building mid-air is annoying. 

[Fixed in next release ](https://github.com/XFactHD/FramedBlocks/commit/55bf215c54a76d74c388175c07652568c3438721)

**Comment by Erysch** [comment]
> > Well, I swapped out the mods already and noticed that the pressure plates do not work properly . The door didn't really move or only one half of it (i used the industrial iron door from 'Dustrial Decor) .
> 
> This sounds like it is working properly, to open a double door you need two pressure plates for each door unless you want to have some redstone below passing the signal along. I just tested it with 'Dustrial Decor iron doors, wooden doors, iron doors, stone pressure plates, framed blocks pressure plates and blockcarpentry pressure plates. They all work the same
> 
> > Also the slope block placement for roofs is annoying since it it's based on the block side you click on. So building mid-air is annoying.
> 
> [Fixed in next release ](https://github.com/XFactHD/FramedBlocks/commit/55bf215c54a76d74c388175c07652568c3438721)

Sry to confuse you. I meant with a half a HALF. So the upper side of the single door moved and the lower side didn't. But most of the time, the door didn't even open at all or move or whatever. 
But ugh okay, good to know that it works for you. Maybe this was a rare bug. I played on multiplayer btw, maybe this caused the problem?

**Comment by Erysch** [comment]
So I just tried to add FramedBlocks but the doors still do not open (playing on server) with the framed pressure plates. This time, I also tried other doors and this appears to any door. Then, suddenly, at some point, it worked for me (using another position and put pink wool in) but then after trying it again it doesn't work again.

**Comment by NillerMedDild** [comment]
> So I just tried to add FramedBlocks but the doors still do not open (playing on server) with the framed pressure plates. This time, I also tried other doors and this appears to any door. Then, suddenly, at some point, it worked for me (using another position and put pink wool in) but then after trying it again it doesn't work again.

I can't reproduce that on a server, could you provide screenshots?

**Comment by Erysch** [comment]
> > So I just tried to add FramedBlocks but the doors still do not open (playing on server) with the framed pressure plates. This time, I also tried other doors and this appears to any door. Then, suddenly, at some point, it worked for me (using another position and put pink wool in) but then after trying it again it doesn't work again.
> 
> I can't reproduce that on a server, could you provide screenshots?

Hey, I just tried again and found out that the door only opens on one side
![Base Profile Screenshot 2021 06 09 - 15 48 24 24](https://user-images.githubusercontent.com/81813584/121367126-5538bd00-c93a-11eb-9a6e-529e31f91ac3.png)
![Base Profile Screenshot 2021 06 09 - 15 48 28 89](https://user-images.githubusercontent.com/81813584/121367131-5669ea00-c93a-11eb-81a9-83a8de092b21.png)
